import { FieldValue } from "firebase-admin/firestore";
import { HttpsError, onCall } from "firebase-functions/v2/https";
import { db, loadConfig, requireString, requireUid } from "../lib/admin.js";
import { addNotification, applyOutcome, readUserContext } from "../lib/engine.js";
import type { RewardDoc } from "../types.js";

/**
 * Atomic claim: verify auth, reward, availability, balance and once-per-user, then deduct
 * and create the claim. claimKey is generated by the client per click, so a network retry
 * of the same click resolves to the same claim without a second deduction.
 */
export const claimReward = onCall(async (request) => {
  const uid = requireUid(request);
  const data = (request.data ?? {}) as { rewardId?: unknown; claimKey?: unknown };
  const rewardId = requireString(data.rewardId, "rewardId", 120);
  const claimKey = requireString(data.claimKey, "claimKey", 80);
  const config = await loadConfig();
  const claimId = `${uid}_${claimKey}`;
  const eventId = `claim_${claimId}`;

  return db.runTransaction(async (txn) => {
    const ctx = await readUserContext(txn, uid, eventId, config);
    const rewardRef = db.doc(`rewards/${rewardId}`);
    const claimRef = db.doc(`rewardClaims/${claimId}`);
    const [rewardSnap, claimSnap] = await txn.getAll(rewardRef, claimRef);
    if (ctx.eventDone || claimSnap.exists) return { alreadyClaimed: true, claimId, ...(claimSnap.data() ?? {}) };
    if (!rewardSnap.exists) throw new HttpsError("not-found", "Reward not found.");
    const reward = rewardSnap.data() as RewardDoc;
    if (!reward.available) throw new HttpsError("failed-precondition", "This reward is not available right now.");
    if (reward.oncePerUser) {
      const prior = await txn.get(db.collection("rewardClaims").where("userId", "==", uid).where("rewardId", "==", rewardId).limit(1));
      if (!prior.empty) throw new HttpsError("already-exists", "You have already claimed this reward.");
    }
    if (ctx.user.stars < reward.starsRequired) {
      throw new HttpsError("failed-precondition", `You need ${reward.starsRequired - ctx.user.stars} more Stars.`);
    }
    txn.set(claimRef, {
      id: claimId,
      userId: uid,
      rewardId,
      rewardName: reward.name,
      starsSpent: reward.starsRequired,
      type: "store",
      status: "pending",
      createdAt: FieldValue.serverTimestamp()
    });
    applyOutcome(txn, ctx, { eventId, reason: "reward_claim", refId: rewardId, xp: 0, stars: -reward.starsRequired });
    addNotification(txn, uid, "reward", "Reward claimed", `${reward.name} is pending fulfilment.`, "/rewards");
    return { alreadyClaimed: false, claimId, starsSpent: reward.starsRequired, remainingStars: ctx.user.stars - reward.starsRequired };
  });
});
